// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/minesweeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Minesweeper_MakeMove_FullMethodName = "/minesweeper.Minesweeper/MakeMove"
	Minesweeper_Reset_FullMethodName    = "/minesweeper.Minesweeper/Reset"
)

// MinesweeperClient is the client API for Minesweeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinesweeperClient interface {
	MakeMove(ctx context.Context, in *Move, opts ...grpc.CallOption) (*GameState, error)
	Reset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GameState, error)
}

type minesweeperClient struct {
	cc grpc.ClientConnInterface
}

func NewMinesweeperClient(cc grpc.ClientConnInterface) MinesweeperClient {
	return &minesweeperClient{cc}
}

func (c *minesweeperClient) MakeMove(ctx context.Context, in *Move, opts ...grpc.CallOption) (*GameState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameState)
	err := c.cc.Invoke(ctx, Minesweeper_MakeMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minesweeperClient) Reset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GameState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameState)
	err := c.cc.Invoke(ctx, Minesweeper_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinesweeperServer is the server API for Minesweeper service.
// All implementations must embed UnimplementedMinesweeperServer
// for forward compatibility.
type MinesweeperServer interface {
	MakeMove(context.Context, *Move) (*GameState, error)
	Reset(context.Context, *Empty) (*GameState, error)
	mustEmbedUnimplementedMinesweeperServer()
}

// UnimplementedMinesweeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinesweeperServer struct{}

func (UnimplementedMinesweeperServer) MakeMove(context.Context, *Move) (*GameState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeMove not implemented")
}
func (UnimplementedMinesweeperServer) Reset(context.Context, *Empty) (*GameState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedMinesweeperServer) mustEmbedUnimplementedMinesweeperServer() {}
func (UnimplementedMinesweeperServer) testEmbeddedByValue()                     {}

// UnsafeMinesweeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinesweeperServer will
// result in compilation errors.
type UnsafeMinesweeperServer interface {
	mustEmbedUnimplementedMinesweeperServer()
}

func RegisterMinesweeperServer(s grpc.ServiceRegistrar, srv MinesweeperServer) {
	// If the following call pancis, it indicates UnimplementedMinesweeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Minesweeper_ServiceDesc, srv)
}

func _Minesweeper_MakeMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Move)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinesweeperServer).MakeMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Minesweeper_MakeMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinesweeperServer).MakeMove(ctx, req.(*Move))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minesweeper_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinesweeperServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Minesweeper_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinesweeperServer).Reset(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Minesweeper_ServiceDesc is the grpc.ServiceDesc for Minesweeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Minesweeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minesweeper.Minesweeper",
	HandlerType: (*MinesweeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeMove",
			Handler:    _Minesweeper_MakeMove_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Minesweeper_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/minesweeper.proto",
}
