// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: proto/minesweeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Action int32 `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_minesweeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minesweeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_minesweeper_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Move) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cell []int32 `protobuf:"zigzag32,1,rep,packed,name=Cell,proto3" json:"Cell,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_minesweeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minesweeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_minesweeper_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetCell() []int32 {
	if x != nil {
		return x.Cell
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board  []*Row `protobuf:"bytes,1,rep,name=Board,proto3" json:"Board,omitempty"`
	State  int32  `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	Reward int32  `protobuf:"varint,3,opt,name=Reward,proto3" json:"Reward,omitempty"`
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_proto_minesweeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minesweeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_minesweeper_proto_rawDescGZIP(), []int{2}
}

func (x *GameState) GetBoard() []*Row {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *GameState) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_minesweeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minesweeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_minesweeper_proto_rawDescGZIP(), []int{3}
}

var File_proto_minesweeper_proto protoreflect.FileDescriptor

var file_proto_minesweeper_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x69, 0x6e, 0x65, 0x73,
	0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x19, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x65, 0x6c,
	0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x11, 0x52, 0x04, 0x43, 0x65, 0x6c, 0x6c, 0x22, 0x61, 0x0a,
	0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x69, 0x6e, 0x65,
	0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x05, 0x42, 0x6f, 0x61,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x7d, 0x0a, 0x0b, 0x4d, 0x69, 0x6e,
	0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x1a, 0x16, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x6d, 0x69, 0x6e,
	0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x6d, 0x69, 0x6e, 0x65,
	0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_minesweeper_proto_rawDescOnce sync.Once
	file_proto_minesweeper_proto_rawDescData = file_proto_minesweeper_proto_rawDesc
)

func file_proto_minesweeper_proto_rawDescGZIP() []byte {
	file_proto_minesweeper_proto_rawDescOnce.Do(func() {
		file_proto_minesweeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_minesweeper_proto_rawDescData)
	})
	return file_proto_minesweeper_proto_rawDescData
}

var file_proto_minesweeper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_minesweeper_proto_goTypes = []any{
	(*Move)(nil),      // 0: minesweeper.Move
	(*Row)(nil),       // 1: minesweeper.Row
	(*GameState)(nil), // 2: minesweeper.GameState
	(*Empty)(nil),     // 3: minesweeper.Empty
}
var file_proto_minesweeper_proto_depIdxs = []int32{
	1, // 0: minesweeper.GameState.Board:type_name -> minesweeper.Row
	0, // 1: minesweeper.Minesweeper.MakeMove:input_type -> minesweeper.Move
	3, // 2: minesweeper.Minesweeper.Reset:input_type -> minesweeper.Empty
	2, // 3: minesweeper.Minesweeper.MakeMove:output_type -> minesweeper.GameState
	2, // 4: minesweeper.Minesweeper.Reset:output_type -> minesweeper.GameState
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_minesweeper_proto_init() }
func file_proto_minesweeper_proto_init() {
	if File_proto_minesweeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_minesweeper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_minesweeper_proto_goTypes,
		DependencyIndexes: file_proto_minesweeper_proto_depIdxs,
		MessageInfos:      file_proto_minesweeper_proto_msgTypes,
	}.Build()
	File_proto_minesweeper_proto = out.File
	file_proto_minesweeper_proto_rawDesc = nil
	file_proto_minesweeper_proto_goTypes = nil
	file_proto_minesweeper_proto_depIdxs = nil
}
